<#
.SYNOPSIS
Assemble a lesson packet from the due queue and prompt templates.

.DESCRIPTION
Reads the daily due queue JSON and prompt templates, then generates a
markdown lesson packet that ChatGPT can consume via the GitHub App.
The packet includes the system prompt, due items with definitions and
learner history, and the JSON output contract.

.CONTEXT
LinguaCircuit — Vocabulary & Idiom Learning System (Phase 1 MVP)

.AUTHOR
Greg Tate

.NOTES
Program: Invoke-LessonPrep.ps1
#>

[CmdletBinding()]
param(
    [string]$LearnerId = 'greg',

    [string]$RepoRoot = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)),

    [string]$DateOverride
)

$Main = {
    . $Helpers

    $today = Get-EffectiveDate
    $dueQueue = Read-DueQueue -Today $today
    $systemPrompt = Read-PromptTemplate -Name 'system'
    $lessonTemplate = Read-PromptTemplate -Name 'lesson'
    $lessonPacket = Build-LessonPacket -Queue $dueQueue -SystemPrompt $systemPrompt -LessonTemplate $lessonTemplate -Today $today
    Export-LessonPacket -Content $lessonPacket -Today $today
}

$Helpers = {

    function Get-EffectiveDate {
        # Determine the effective date for lesson prep
        if ($DateOverride) {
            return [datetime]::Parse($DateOverride).Date
        }
        return (Get-Date).Date
    }

    function Read-DueQueue {
        # Load the due queue JSON generated by Get-DueItems.ps1
        param([datetime]$Today)

        $dateStr = $Today.ToString('yyyy-MM-dd')
        $queuePath = Join-Path $RepoRoot "data\derived\due-queues\$dateStr.json"

        if (-not (Test-Path $queuePath)) {
            throw "Due queue not found for $dateStr. Run Get-DueItems.ps1 first."
        }

        Get-Content $queuePath -Raw | ConvertFrom-Json
    }

    function Read-PromptTemplate {
        # Load a prompt template by name from the prompts directory
        param([string]$Name)

        $promptPath = Join-Path $RepoRoot "prompts\$Name.md"
        if (-not (Test-Path $promptPath)) {
            throw "Prompt template not found: $promptPath"
        }

        Get-Content $promptPath -Raw
    }

    function Build-LessonPacket {
        # Assemble the full lesson markdown from queue data and templates
        param(
            [object]$Queue,
            [string]$SystemPrompt,
            [string]$LessonTemplate,
            [datetime]$Today
        )

        $dateStr = $Today.ToString('yyyy-MM-dd')
        $itemCount = $Queue.total_items

        # Build the items section
        $itemsSection = Build-ItemSection -Items $Queue.items

        # Build the learner context section
        $learnerContext = Build-LearnerContext -Items $Queue.items

        # Assemble the full packet
        $packet = @"
# LinguaCircuit Daily Lesson — $dateStr

**Learner:** $($Queue.learner_id)
**Items to review:** $itemCount

---

## System Instructions

$SystemPrompt

---

## Today's Items

$itemsSection

---

## Learner Context

$learnerContext

---

## Lesson Instructions

$LessonTemplate

---

*Generated: $(Get-Date -Format 'o')*
"@

        return $packet
    }

    function Build-ItemSection {
        # Format each due item into a readable markdown block
        param([object[]]$Items)

        $sections = $Items | ForEach-Object {
            $item = $_
            $def = $item.definition

            $block = @"

### $($def.term) ($($def.item_type))

- **Definition:** $($def.definition)
- **Part of speech:** $($def.part_of_speech)
- **Difficulty:** $($def.difficulty)/5
- **Status:** $($item.status) | **Due:** $($item.next_due) | **Ease:** $($item.ease)
"@

            # Add etymology if available
            if ($def.etymology -and $def.etymology.origin_summary) {
                $block += "`n- **Etymology:** $($def.etymology.origin_summary)"
            }

            # Add literal gloss for idioms
            if ($def.literal_gloss) {
                $block += "`n- **Literal gloss:** $($def.literal_gloss)"
                $block += "`n- **Figurative meaning:** $($def.figurative_meaning)"
                $block += "`n- **Register:** $($def.register)"
            }

            # Add examples
            if ($def.examples) {
                $block += "`n- **Examples:**"
                $def.examples | ForEach-Object {
                    $block += "`n  - $_"
                }
            }

            # Add confusions
            if ($def.confusions) {
                $block += "`n- **Commonly confused with:**"
                $def.confusions | ForEach-Object {
                    $block += "`n  - **$($_.term):** $($_.difference)"
                }
            }

            # Add usage notes
            if ($def.usage_notes) {
                $block += "`n- **Usage notes:**"
                $def.usage_notes | ForEach-Object {
                    $block += "`n  - $_"
                }
            }

            $block
        }

        $sections -join "`n"
    }

    function Build-LearnerContext {
        # Summarize learner performance history for the due items
        param([object[]]$Items)

        $context = @"
| Item | Status | Last Reviewed | Lapse Count | Recall (Def/Usage/Root) |
|------|--------|--------------|-------------|-------------------------|
"@

        $Items | ForEach-Object {
            $rd = $_.recall_dimensions
            $defScore = if ($rd) { $rd.definition } else { '-' }
            $usageScore = if ($rd) { $rd.sentence_usage } else { '-' }
            $rootScore = if ($rd) { $rd.root_understanding } else { '-' }
            $lastRev = if ($_.last_reviewed) { $_.last_reviewed } else { 'never' }
            $context += "`n| $($_.item_id) | $($_.status) | $lastRev | $($_.lapse_count) | $defScore / $usageScore / $rootScore |"
        }

        return $context
    }

    function Export-LessonPacket {
        # Write the assembled lesson packet to the derived/due-queues folder
        param(
            [string]$Content,
            [datetime]$Today
        )

        $dateStr = $Today.ToString('yyyy-MM-dd')
        $outputDir = Join-Path $RepoRoot "data\derived\due-queues"

        if (-not (Test-Path $outputDir)) {
            New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
        }

        $outputPath = Join-Path $outputDir "$dateStr-lesson.md"
        Set-Content -Path $outputPath -Value $Content -Encoding utf8
        Write-Host "Lesson packet written: $outputPath"
    }
}

try {
    Push-Location -Path $PSScriptRoot
    & $Main
}
finally {
    Pop-Location
}
